export enum SessionStatus {
    IDLE = 'IDLE',
    QRCODE = 'QRCODE',
    AUTHENTICATING = 'AUTHENTICATING',
    CONNECTING = 'CONNECTING',
    CONNECTED = 'CONNECTED',
    DISCONNECTED = 'DISCONNECTED',
}